/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Controlador2;
import Logica.Datatypes.DataFecha;
import Logica.Datatypes.DataP;
import Logica.Datatypes.dataPerfil;
import java.awt.Image;

import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicole
 */
public class ConsultaPerfil extends javax.swing.JFrame {
  
//DefaultComboBox modell = new DefaultComboBox();
 DefaultComboBoxModel modell = new DefaultComboBoxModel();
Controlador2 cont2 = Controlador2.getInstance();
// String paraImagen=null;
// Controlador2 cont2 = new Controlador2();
    /**
     * Creates new form ConsultaPerfil
     */
    public ConsultaPerfil() {
         initComponents();
       CargarComboBox();  
        
       //   setLocationRelativeTo(null);
         
       
    }
public void CargarComboBox(){
    List al=cont2.listarP();
    Iterator it = al.iterator();
  
       while(it.hasNext()){  
            DataP a=(DataP)it.next();
                
               modell.addElement(a.getNick());
               
            }
            combo1.setModel(modell); 

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b_mostrar = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox();
        salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mostrarurl = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(745, 453));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Consulta de Perfil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 360, 48);

        b_mostrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_mostrar.setForeground(new java.awt.Color(0, 51, 102));
        b_mostrar.setText("Mostrar");
        b_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(b_mostrar);
        b_mostrar.setBounds(510, 370, 90, 30);

        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(combo1);
        combo1.setBounds(200, 70, 242, 30);

        salir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 51, 102));
        salir.setText("Cancelar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(630, 370, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Selecionar Perfil");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 70, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(301, 129, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("                                   ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(452, 129, 140, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("                                                    ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(452, 157, 208, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Apellido");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(311, 157, 70, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(231, 192, 150, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("                                 ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(452, 192, 132, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("Nick");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(331, 228, 50, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("                                      ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(452, 228, 152, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 102));
        jLabel14.setText("Correo Electronico");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(241, 263, 140, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("                                           ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(452, 263, 172, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("WebURL");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(320, 330, 60, 20);

        mostrarurl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mostrarurl.setText("                                                    ");
        getContentPane().add(mostrarurl);
        mostrarurl.setBounds(450, 330, 208, 17);

        foto.setText("jLabel3");
        getContentPane().add(foto);
        foto.setBounds(60, 190, 130, 120);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("Perfil");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(321, 298, 60, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("                                                    ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(450, 300, 208, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrador\\Music\\TAREA13333\\fondoprograma.jpg")); // NOI18N
        jLabel2.setText("dfdf");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 1210, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_mostrarActionPerformed
//       
      String d= (String )combo1.getSelectedItem();
      if(d==null){
           JOptionPane.showMessageDialog (null, "No hay perfil selecionado");
      }else{
        dataPerfil dp= cont2.selecPerfil(d);
        DataFecha f =dp.fechaNacim;
       jLabel7.setText(dp.nombre); 
       jLabel8.setText(dp.apellido);
       
       
       jLabel11.setText(dp.fechaNacim.getFecha(f));
       
       jLabel13.setText(dp.nick);
       jLabel15.setText(dp.correo);
      jLabel19.setText(dp.DameTipo());
      mostrarurl.setText(cont2.findD(dp.nick).getWebURL());
       ImageIcon imagen = new ImageIcon(dp.imagen);
       Icon icono = new ImageIcon (imagen.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(),Image.SCALE_DEFAULT));
       foto.setIcon(icono);
       this.repaint();
       //        foto.setBounds(60, 190, 130, 120);
        //foto.setIcon(new javax.swing.ImageIcon
               // (dp.imagen).getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), null));
//        foto.setBounds(60, 190, 130, 120);
        
      }
        
    }//GEN-LAST:event_b_mostrarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
           // TODO add your handling code here:
        this.setVisible(false);
      Inicio view;
        view = new Inicio();
      view.setVisible(true); 
    }//GEN-LAST:event_salirActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
//String d = combo1.getComponents().toString();
//        dataPerfil dp= cont2.selecPerfil(d);
//        jLabel8.setText(dp.nombre); 
        
    }//GEN-LAST:event_combo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConsultaPerfil().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_mostrar;
    private javax.swing.JComboBox combo1;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mostrarurl;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
